/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	double a;
	double b;
};
typedef struct numeros numeros;

#define RAND_PROG 0x31111111
#define RAND_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  double * suma_1(numeros *, CLIENT *);
extern  double * suma_1_svc(numeros *, struct svc_req *);
#define resta 2
extern  double * resta_1(numeros *, CLIENT *);
extern  double * resta_1_svc(numeros *, struct svc_req *);
#define multi 3
extern  double * multi_1(numeros *, CLIENT *);
extern  double * multi_1_svc(numeros *, struct svc_req *);
#define divi 4
extern  double * divi_1(numeros *, CLIENT *);
extern  double * divi_1_svc(numeros *, struct svc_req *);
extern int rand_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define resta 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define multi 3
extern  double * multi_1();
extern  double * multi_1_svc();
#define divi 4
extern  double * divi_1();
extern  double * divi_1_svc();
extern int rand_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);

#else /* K&R C */
extern bool_t xdr_numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
